INSERT INTO chapitres VALUES('1', '1', '', 'vide');
INSERT INTO chapitres VALUES('2', '1', 'Attentif tu seras', 'vide');
INSERT INTO chapitres VALUES('3', '1', 'Des notes tu prendras', 'vide');
INSERT INTO chapitres VALUES('4', '1', 'Silencieux tu seras', 'vide');
INSERT INTO chapitres VALUES('5', '1', 'Dormir tu éviteras', 'vide');
INSERT INTO chapitres VALUES('6', '1', 'Poser des questions tu n\'hésiteras pas', 'vide');
INSERT INTO chapitres VALUES('7', '1', 'Avec les autres tu échangeras', 'vide');
INSERT INTO chapitres VALUES('8', '1', 'Des livres du cours tu t\'aideras', 'vide');
INSERT INTO chapitres VALUES('9', '1', 'Pratiquer, tester, essayer ... tu n\'hésiteras pas', 'vide');
INSERT INTO chapitres VALUES('10', '1', 'Tes écouteurs tu oteras', 'vide');
INSERT INTO chapitres VALUES('11', '1', 'Ton téléphone tu rangeras', 'vide');
INSERT INTO chapitres VALUES('12', '1', 'En classe tu te découvriras', 'vide');
INSERT INTO chapitres VALUES('13', '1', 'De 12h00 à 13h15 tu te sustenteras', 'vide');
INSERT INTO chapitres VALUES('14', '1', 'En classe vous n\'êtes plus', 'vide');

INSERT INTO chapitres VALUES(NULL, '2', 'Configuration matérielle', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Configuration logicielle', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Avertissement !', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Configuration Windows', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Connexion au réseau de l\'école', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Vérification rapide de la configuration réseau', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Accès à HUGO', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Configuration de l\'imprimante sous Windows', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Logiciels complémentaires', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Installation VirtualBox', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Création d\'une machine virtuelle Linux', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Firefox', 'vide');
INSERT INTO chapitres VALUES(NULL, '2', 'Configuration Firefox', 'vide');
